#!/usr/bin/env python3
"""Generate demo/charset-manifest.ts from fonts/imported/*.woff2.

The showcase's Character Set window picks a face and a size and renders that
strike's full coverage; this script gives it the data — per strike, the
characters its cmap actually carries (so the specimen can never show a
system-font fallback) and the font-rect line height the strike renders at
(upm / 64: one design px per system px at `font-size: <line>px`).

Only `<Family>-<n>.woff2` names are read — the kit's re-emmed builds
(`Chicago-12-em16`, `Geneva-9-em16-a12`) are intermediate artifacts of the
embedded faces, not collection members. Run after (re)building the
collection:

    /tmp/fontenv/bin/python3 fonts/charset-manifest.py
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
IMPORTED = ROOT / "fonts" / "imported"
OUT = ROOT / "demo" / "charset-manifest.ts"

STRIKE = re.compile(r"^([A-Za-z]+)-(\d+)\.woff2$")

# Display names for the families whose filenames squeeze the spaces out.
PRETTY = {
    "NewYork": "New York",
    "LosAngeles": "Los Angeles",
    "SanFrancisco": "San Francisco",
    "EspySans": "Espy Sans",
    "EspySansBold": "Espy Sans Bold",
    "EspySerif": "Espy Serif",
    "EspySerifBold": "Espy Serif Bold",
    "EWorldTight": "eWorld Tight",
}

# Families still named by font-rect line height — their point size is
# undetermined (fonts/README.md, "The collection's names").
LINE_NAMED = {
    "System",
    "SwanSong",
    "Mobile",
    "Taliesin",
    "EspySans",
    "EspySansBold",
    "EspySerif",
    "EspySerifBold",
    "EWorldTight",
}


def visible(cp: int) -> bool:
    """Codepoints worth a slot in the specimen: no controls, no blanks."""
    if cp <= 0x20 or 0x7F <= cp <= 0xA0 or cp == 0xAD:
        return False
    return True


def main() -> None:
    families: dict[str, list[dict]] = {}
    for path in sorted(IMPORTED.glob("*.woff2")):
        match = STRIKE.match(path.name)
        if not match:
            continue
        stem, size = match.group(1), int(match.group(2))
        font = TTFont(path, lazy=True)
        upm = font["head"].unitsPerEm
        assert upm % 64 == 0, f"{path.name}: upm {upm} is not on the 64-unit grid"
        chars = "".join(chr(cp) for cp in sorted(font.getBestCmap()) if visible(cp))
        font.close()
        families.setdefault(stem, []).append(
            {"size": size, "line": upm // 64, "file": path.name, "chars": chars}
        )

    entries = []
    for stem in sorted(families, key=lambda s: PRETTY.get(s, s).casefold()):
        fonts = sorted(families[stem], key=lambda f: f["size"])
        rows = ",\n".join(
            "      { size: %d, line: %d, file: %s, chars:\n        %s }"
            % (f["size"], f["line"], json.dumps(f["file"]), json.dumps(f["chars"]))
            for f in fonts
        )
        entries.append(
            "  {\n    label: %s,\n    sizeIsLine: %s,\n    fonts: [\n%s,\n    ],\n  }"
            % (
                json.dumps(PRETTY.get(stem, stem)),
                "true" if stem in LINE_NAMED else "false",
                rows,
            )
        )

    OUT.write_text(
        "/* GENERATED by fonts/charset-manifest.py — do not hand-edit.\n"
        " * Regenerate after rebuilding fonts/imported/:\n"
        " *   /tmp/fontenv/bin/python3 fonts/charset-manifest.py\n"
        " */\n\n"
        "export interface CharsetFont {\n"
        "  /** The number the collection names the strike by (see sizeIsLine). */\n"
        "  size: number\n"
        "  /** Font-rect line height in design px — render at font-size: <line>px\n"
        "   *  for one design px per system px (the 64-unit grid). */\n"
        "  line: number\n"
        "  /** Filename under fonts/imported/ (untracked — built locally). */\n"
        "  file: string\n"
        "  /** Every visible character the strike's cmap carries, by codepoint. */\n"
        "  chars: string\n"
        "}\n\n"
        "export interface CharsetFamily {\n"
        "  label: string\n"
        "  /** True where the collection still names by line height — the point\n"
        "   *  size is undetermined (fonts/README.md). */\n"
        "  sizeIsLine: boolean\n"
        "  fonts: CharsetFont[]\n"
        "}\n\n"
        "export const CHARSET_FAMILIES: CharsetFamily[] = [\n"
        + ",\n".join(entries)
        + ",\n]\n"
    )
    strikes = sum(len(f) for f in families.values())
    print(f"charset-manifest: {len(families)} families, {strikes} strikes → {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
