/**
 * Regenerates src/build/frame-picture.ts from box/frame.png: the picture of
 * the kit's frame, which every app file's box is drawn on. Its slots are
 * src/build/frame.ts's, kept by hand; move them with the picture.
 *
 * Embedded as base64 for the reason the faces and the cursors are: the
 * package ships no asset files, so the build entry finds its frame in the
 * module graph, under Node or a bundler alike.
 *
 *   npm run embed:frame
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const png = readFileSync(join(ROOT, 'box/frame.png'))
if (!png.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]))) {
  throw new Error('box/frame.png is not a PNG')
}
const width = png.readUInt32BE(16)
const height = png.readUInt32BE(20)

const out = `/**
 * The kit's frame's picture: box/frame.png, ${width} × ${height}, ${png.length} bytes.
 * GENERATED by \`npm run embed:frame\`: redraw box/frame.png and re-run rather
 * than editing this file. Its slots are src/build/frame.ts's.
 */
export const FRAME_PNG: Uint8Array = Uint8Array.from(atob('${png.toString('base64')}'), (ch) => ch.charCodeAt(0))
`

writeFileSync(join(ROOT, 'src/build/frame-picture.ts'), out)
console.log(`src/build/frame-picture.ts: box/frame.png, ${width} × ${height}, ${png.length} bytes`)
