/**
 * Verifies `vf-alert variant="caution"` — the one piece of raster art the
 * library itself ships (src/icons.ts, generated by `npm run extract:icons`).
 *
 * The icon is the reference sheet's own 32x32 System 7 caution icon rather than
 * a redrawing of it, because an alert icon is a *picture* and the kit does not
 * vectorize pictures. That decision costs something the inline SVG got for
 * free: an SVG is resolution-independent and cannot smear, while a magnified
 * bitmap is crisp only while its box stays a whole number of device pixels.
 * So this asserts the rendered ink, not the CSS that produces it:
 *
 *  - COUNT: exactly 242 art pixels are ink (that is what the sheet crop
 *    contains), so at N device px per system px the icon must paint exactly
 *    242 x N^2 black device px — the count nearest-neighbor magnification
 *    guarantees and bilinear smoothing does not.
 *  - PURITY: every pixel in the icon's box is pure black or pure white. One
 *    gray pixel means an edge landed between device rows, which is the whole
 *    failure mode a bitmap has and a vector doesn't.
 *  - SHAPE: the magnified image is the source bitmap scaled by N exactly —
 *    every device pixel matches the art pixel it comes from. This is what
 *    separates "crisp" from "crisp but resampled a row short".
 *  - MASK: the art is black-on-transparent and paints as an alpha mask over
 *    --vf-black, so the ink retints with the token and the triangle's interior
 *    shows the surface behind it rather than a baked-in white. Both are
 *    checked by rethemeing, since an <img> would pass every check above and
 *    fail these two.
 *  - PARITY: the same icon, ink for ink, as demo/icons/alert.png — the two are
 *    cut from one crop and must not drift.
 *
 * All at dpr 1 / 2 / 3, where --vf-scale self-selects 3 / dpr.
 *
 *   npm run dev        # in another shell (port 5173)
 *   npm run verify:caution
 */
import { chromium } from 'playwright'
import { inflateSync } from 'node:zlib'
import { readFileSync } from 'node:fs'

const ORIGIN = process.env.VF_ORIGIN ?? 'http://localhost:5173/'
const DENSITIES = (process.env.VF_CAUTION_DPR ?? '1,2,3').split(',').map(Number)

/** The art's own grid: a System 7 large icon cell. */
const ART = 32

// ── minimal PNG decode (8-bit RGBA/RGB, non-interlaced) ──────────────────
function decodePng(buf) {
  let pos = 8
  let ihdr
  const idat = []
  while (pos < buf.length) {
    const len = buf.readUInt32BE(pos)
    const type = buf.toString('ascii', pos + 4, pos + 8)
    if (type === 'IHDR') ihdr = buf.subarray(pos + 8, pos + 8 + len)
    else if (type === 'IDAT') idat.push(buf.subarray(pos + 8, pos + 8 + len))
    pos += 12 + len
  }
  const width = ihdr.readUInt32BE(0)
  const height = ihdr.readUInt32BE(4)
  const bpp = ihdr[9] === 6 ? 4 : 3
  const raw = inflateSync(Buffer.concat(idat))
  const stride = width * bpp
  const out = Buffer.alloc(height * stride)
  for (let y = 0; y < height; y++) {
    const filter = raw[y * (stride + 1)]
    const row = raw.subarray(y * (stride + 1) + 1, (y + 1) * (stride + 1))
    const prev = y > 0 ? out.subarray((y - 1) * stride, y * stride) : null
    const cur = out.subarray(y * stride, (y + 1) * stride)
    for (let x = 0; x < stride; x++) {
      const a = x >= bpp ? cur[x - bpp] : 0
      const b = prev ? prev[x] : 0
      const c = x >= bpp && prev ? prev[x - bpp] : 0
      let v = row[x]
      switch (filter) {
        case 1: v += a; break
        case 2: v += b; break
        case 3: v += (a + b) >> 1; break
        case 4: {
          const p = a + b - c
          const pa = Math.abs(p - a)
          const pb = Math.abs(p - b)
          const pc = Math.abs(p - c)
          v += pa <= pb && pa <= pc ? a : pb <= pc ? b : c
          break
        }
      }
      cur[x] = v & 0xff
    }
  }
  return { width, height, bpp, data: out }
}

const px = (png, x, y) => {
  const i = (y * png.width + x) * png.bpp
  return [png.data[i], png.data[i + 1], png.data[i + 2]]
}

/** The source art as a boolean ink mask, straight off the extracted PNG. */
function artMask() {
  const src = decodePng(readFileSync('demo/icons/alert.png'))
  const mask = []
  for (let y = 0; y < ART; y++) {
    const row = []
    for (let x = 0; x < ART; x++) {
      const i = (y * src.width + x) * src.bpp
      const alpha = src.bpp === 4 ? src.data[i + 3] : 255
      row.push(alpha >= 128 && src.data[i] < 128)
    }
    mask.push(row)
  }
  return mask
}

const ART_MASK = artMask()
const ART_INK = ART_MASK.flat().filter(Boolean).length

const results = []
function check(name, pass, detail = '') {
  results.push(pass)
  console.log(`  ${pass ? 'ok  ' : 'FAIL'} ${name}${detail ? `   ${detail}` : ''}`)
}

const browser = await chromium.launch()

/** Open an alert on a blank page and screenshot just its icon column. */
async function shootIcon(dpr, { tokens = '', variant = 'caution', slotted = '' } = {}) {
  const page = await browser.newPage({
    viewport: { width: 700, height: 400 },
    deviceScaleFactor: dpr,
  })
  await page.route(ORIGIN, (route) =>
    route.fulfill({ contentType: 'text/html', body: '<!doctype html><meta charset="utf-8">' })
  )
  await page.goto(ORIGIN)
  await page.unroute(ORIGIN)
  await page.setContent(
    `<!doctype html><meta charset="utf-8">` +
      `<body style="margin:0;background:#fff;padding:24px;${tokens}">` +
      `<vf-alert id="a" ${variant ? `variant="${variant}"` : ''} label="Caution" ` +
      `width="340" height="118" open>${slotted}` +
      `<vf-paragraph>Erase the disk?</vf-paragraph>` +
      `<vf-button slot="buttons" variant="default">OK</vf-button></vf-alert>`
  )
  await page.evaluate(() => import('/src/index.js'))
  await page.evaluate(() =>
    Promise.all(
      [...document.querySelectorAll('*')]
        .filter((e) => e.tagName.toLowerCase().startsWith('vf-'))
        .map((e) => e.updateComplete)
    )
  )
  await page.evaluate(() => document.fonts.ready)
  await page.evaluate(
    () => new Promise((r) => requestAnimationFrame(() => requestAnimationFrame(r)))
  )

  const geo = await page.evaluate(() => {
    const host = document.getElementById('a')
    const col = host.shadowRoot.querySelector('[part="icon"]')
    // The variant's own element, or — when the consumer slotted one — whatever
    // the icon slot got assigned. The slot itself has no box to measure.
    const icon =
      host.shadowRoot.querySelector('.caution') ??
      col.querySelector('slot')?.assignedElements()[0] ??
      col
    const r = (icon ?? col).getBoundingClientRect()
    return {
      scale: parseFloat(getComputedStyle(host).getPropertyValue('--vf-scale')),
      column: col.getBoundingClientRect().width,
      box: { x: r.x, y: r.y, w: r.width, h: r.height },
      isMask: icon ? getComputedStyle(icon).maskImage !== 'none' : false,
    }
  })
  const shot = await page.screenshot({
    clip: { x: geo.box.x, y: geo.box.y, width: geo.box.w, height: geo.box.h },
  })
  await page.close()
  return { ...geo, png: decodePng(shot) }
}

for (const dpr of DENSITIES) {
  const cell = 3 // device px per system px: --vf-scale (3/dpr) x dpr
  console.log(`\nvariant="caution"  dpr ${dpr}`)
  const { png, scale, column, box, isMask } = await shootIcon(dpr)

  check(
    'icon fills the 32-system-px column',
    Math.abs(box.w - ART * scale) < 0.01 && Math.abs(column - ART * scale) < 0.01,
    `${box.w}css = ${ART}sys, column ${column}css`
  )
  check(
    'box is a whole number of device px',
    Math.abs(png.width - ART * cell) < 0.01 && Math.abs(png.height - ART * cell) < 0.01,
    `${png.width}x${png.height} device px`
  )

  let ink = 0
  let smoothed = 0
  let wrong = 0
  for (let y = 0; y < png.height; y++) {
    for (let x = 0; x < png.width; x++) {
      const [r, g, b] = px(png, x, y)
      const black = r < 32 && g < 32 && b < 32
      const white = r > 224 && g > 224 && b > 224
      if (black) ink++
      if (!black && !white) smoothed++
      // Every device px must match the art px it magnifies from.
      const want = ART_MASK[Math.floor(y / cell)][Math.floor(x / cell)]
      if (black !== want) wrong++
    }
  }
  check('COUNT   every art pixel magnified whole', ink === ART_INK * cell * cell,
    `${ink} ink device px (want ${ART_INK} x ${cell}^2 = ${ART_INK * cell * cell})`)
  check('PURITY  nothing between black and white', smoothed === 0,
    `${smoothed} smoothed px`)
  check('SHAPE   magnification is the source bitmap', wrong === 0,
    `${wrong} px differ from the art`)
  check('MASK    painted as a mask, not an <img>', isMask === true, `maskImage set: ${isMask}`)
}

// The mask is what makes the ink themeable and the interior see-through; an
// <img> of the same art would pass every geometric check above and fail here.
console.log('\nthemeability (dpr 2)')
{
  const { png } = await shootIcon(2, {
    tokens: '--vf-black:#0000ff;--vf-white:#ffff00;--vf-surface:#ffff00;',
  })
  let blue = 0
  let yellow = 0
  let other = 0
  for (let y = 0; y < png.height; y++) {
    for (let x = 0; x < png.width; x++) {
      const [r, g, b] = px(png, x, y)
      if (r < 32 && g < 32 && b > 224) blue++
      else if (r > 224 && g > 224 && b < 32) yellow++
      else other++
    }
  }
  check('ink retints with --vf-black', blue === ART_INK * 9 && other === 0,
    `${blue} ink px, ${other} unexpected`)
  check('triangle interior shows the surface, not baked white', yellow > 0,
    `${yellow} surface px inside the box`)
}

// A slotted icon must still win, and must turn the column on by itself.
console.log('\nicon slot still overrides the variant (dpr 2)')
{
  const { png } = await shootIcon(2, {
    variant: '',
    slotted: '<vf-img slot="icon" width="32" height="32">' +
      '<img src="/demo/icons/puzzle.png" alt=""></vf-img>',
  })
  let ink = 0
  for (let y = 0; y < png.height; y++)
    for (let x = 0; x < png.width; x++) {
      const [r, g, b] = px(png, x, y)
      if (r < 32 && g < 32 && b < 32) ink++
    }
  check('slotted art replaces the caution icon', ink !== ART_INK * 9,
    `${ink} ink px (caution would be ${ART_INK * 9})`)
}

await browser.close()

const failed = results.filter((r) => !r).length
console.log(
  failed
    ? `\n${failed} of ${results.length} caution checks FAILED.`
    : `\nAll ${results.length} caution checks passed.`
)
process.exit(failed ? 1 : 0)
