// GENERATED by fonts/add-glyphs.py — do not edit. Every glyph the
// kit adds to the shipped faces, with its bitmap (top row first,
// '#' = ink), placement in design px (y0 = bottom edge, baseline 0)
// and provenance. Rendered by glyph-proof.html.
export interface BackfillGlyph {
  face: string
  char: string
  name: string
  codepoint: number
  rows: string[]
  x0: number
  y0: number
  advance: number
  source: string
}

export const BACKFILL_GLYPHS: BackfillGlyph[] = [
  {
    "face": "VF Display",
    "char": "×",
    "name": "multiply",
    "codepoint": 215,
    "rows": [
      "#...#",
      ".#.#.",
      "..#..",
      ".#.#.",
      "#...#"
    ],
    "x0": 1,
    "y0": 2,
    "advance": 7,
    "source": "drawn — the saltire in the strike's own + box, on the math axis"
  },
  {
    "face": "VF Body",
    "char": "×",
    "name": "multiply",
    "codepoint": 215,
    "rows": [
      "#...#",
      ".#.#.",
      "..#..",
      ".#.#.",
      "#...#"
    ],
    "x0": 0,
    "y0": 1,
    "advance": 6,
    "source": "drawn — the saltire in the strike's own + box, on the math axis"
  },
  {
    "face": "VF Body",
    "char": "⌘",
    "name": "command",
    "codepoint": 8984,
    "rows": [
      ".##...##.",
      "#..#.#..#",
      "#..#.#..#",
      ".#######.",
      "...#.#...",
      ".#######.",
      "#..#.#..#",
      "#..#.#..#",
      ".##...##."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 10,
    "source": "traced — Chicago's ⌘, verbatim, on Geneva's flush-left spacing"
  },
  {
    "face": "VF Body",
    "char": "✓",
    "name": "checkmark",
    "codepoint": 10003,
    "rows": [
      "........#",
      ".......##",
      "......##.",
      ".....##..",
      "#...##...",
      "##.##....",
      ".###.....",
      "..#......"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 10,
    "source": "traced — Chicago's ✓, verbatim, on Geneva's flush-left spacing"
  },
  {
    "face": "VF Body",
    "char": "€",
    "name": "euro",
    "codepoint": 8364,
    "rows": [
      ".###.",
      "#....",
      "#####",
      "#....",
      "#####",
      "#....",
      ".###."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 6,
    "source": "drawn — the strike's own C, curve left open (its corner stubs dropped), crossed by two full-width bars (the € postdates every source strike)"
  },
  {
    "face": "VF Body",
    "char": "−",
    "name": "minus",
    "codepoint": 8722,
    "rows": [
      "#####"
    ],
    "x0": 0,
    "y0": 3,
    "advance": 6,
    "source": "derived — the crossbar of the strike's own +, alone on the math axis"
  },
  {
    "face": "VF Body",
    "char": "·",
    "name": "periodcentered",
    "codepoint": 183,
    "rows": [
      "#"
    ],
    "x0": 1,
    "y0": 3,
    "advance": 3,
    "source": "derived — the strike's period dot raised to the math axis, its bearing kept"
  },
  {
    "face": "VF Body",
    "char": "¹",
    "name": "onesuperior",
    "codepoint": 185,
    "rows": [
      ".#",
      "##",
      ".#",
      ".#",
      ".#"
    ],
    "x0": 0,
    "y0": 2,
    "advance": 3,
    "source": "drawn — a 2x5 digit at superscript height (top at cap height)"
  },
  {
    "face": "VF Body",
    "char": "²",
    "name": "twosuperior",
    "codepoint": 178,
    "rows": [
      "##.",
      "..#",
      ".#.",
      "#..",
      "###"
    ],
    "x0": 0,
    "y0": 2,
    "advance": 4,
    "source": "drawn — a 3x5 digit at superscript height"
  },
  {
    "face": "VF Body",
    "char": "³",
    "name": "threesuperior",
    "codepoint": 179,
    "rows": [
      "##.",
      "..#",
      ".#.",
      "..#",
      "##."
    ],
    "x0": 0,
    "y0": 2,
    "advance": 4,
    "source": "drawn — a 3x5 digit at superscript height"
  },
  {
    "face": "VF Body",
    "char": "½",
    "name": "onehalf",
    "codepoint": 189,
    "rows": [
      ".#.......",
      "##...#...",
      ".#...#...",
      ".#..#....",
      "....#.##.",
      "...#....#",
      "...#...#.",
      "......###"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 10,
    "source": "drawn — mini 1 over mini 2 across a fraction slash, full cap band"
  },
  {
    "face": "VF Body",
    "char": "¼",
    "name": "onequarter",
    "codepoint": 188,
    "rows": [
      ".#.......",
      "##...#...",
      ".#...#...",
      ".#..#....",
      "....#.#.#",
      "...#..#.#",
      "...#..###",
      "........#"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 10,
    "source": "drawn — mini 1 over mini 4 across a fraction slash"
  },
  {
    "face": "VF Body",
    "char": "¾",
    "name": "threequarters",
    "codepoint": 190,
    "rows": [
      "##.......",
      "..#..#...",
      ".#...#...",
      "..#.#....",
      "##..#.#.#",
      "...#..#.#",
      "...#..###",
      "........#"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 10,
    "source": "drawn — the superscript ³ drawing over mini 4, matching ¼'s slash and denominator"
  },
  {
    "face": "VF Body",
    "char": "′",
    "name": "prime",
    "codepoint": 8242,
    "rows": [
      ".#",
      ".#",
      "#."
    ],
    "x0": 1,
    "y0": 4,
    "advance": 4,
    "source": "derived — the strike's ’ ink, dropped to sit on the x-height band"
  },
  {
    "face": "VF Body",
    "char": "″",
    "name": "doubleprime",
    "codepoint": 8243,
    "rows": [
      ".#..#",
      ".#..#",
      "#..#."
    ],
    "x0": 1,
    "y0": 4,
    "advance": 7,
    "source": "derived — two of the strike's ’ ink, one gap apart"
  },
  {
    "face": "VF Body",
    "char": "‚",
    "name": "quotesinglbase",
    "codepoint": 8218,
    "rows": [
      ".#",
      ".#",
      "#."
    ],
    "x0": 1,
    "y0": -2,
    "advance": 4,
    "source": "traced — the strike's comma, verbatim (a low-9 quote is a comma)"
  },
  {
    "face": "VF Body",
    "char": "„",
    "name": "quotedblbase",
    "codepoint": 8222,
    "rows": [
      ".#..#",
      ".#..#",
      "#..#."
    ],
    "x0": 1,
    "y0": -2,
    "advance": 7,
    "source": "derived — the strike's comma, doubled one gap apart"
  },
  {
    "face": "VF Body",
    "char": "‡",
    "name": "daggerdbl",
    "codepoint": 8225,
    "rows": [
      ".#.",
      "###",
      ".#.",
      ".#.",
      "###",
      ".#."
    ],
    "x0": 0,
    "y0": 2,
    "advance": 4,
    "source": "derived — the strike's † with its own crossbar repeated below"
  },
  {
    "face": "VF Body",
    "char": "‹",
    "name": "guilsinglleft",
    "codepoint": 8249,
    "rows": [
      "..#",
      ".#.",
      "#..",
      ".#.",
      "..#"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 5,
    "source": "derived — one chevron of the strike's «"
  },
  {
    "face": "VF Body",
    "char": "›",
    "name": "guilsinglright",
    "codepoint": 8250,
    "rows": [
      "#..",
      ".#.",
      "..#",
      ".#.",
      "#.."
    ],
    "x0": 1,
    "y0": 0,
    "advance": 5,
    "source": "derived — one chevron of the strike's », its bearing kept"
  },
  {
    "face": "VF Body",
    "char": "⁄",
    "name": "fraction",
    "codepoint": 8260,
    "rows": [
      "...#",
      "...#",
      "..#.",
      "..#.",
      ".#..",
      ".#..",
      "#...",
      "#..."
    ],
    "x0": 1,
    "y0": 0,
    "advance": 6,
    "source": "traced — the strike's /, verbatim (one drawing serves both slashes at 9pt)"
  },
  {
    "face": "VF Body",
    "char": "‰",
    "name": "perthousand",
    "codepoint": 8240,
    "rows": [
      ".#######...",
      "#..#..#....",
      "#..#.#.....",
      ".##..##.##.",
      "...##..#..#",
      "..#.#..#..#",
      ".#...##.##."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 12,
    "source": "derived — the strike's % with its lower loop doubled into a shared-wall 00 (Adam's ink, 2026-08-09)"
  },
  {
    "face": "VF Body",
    "char": "ﬁ",
    "name": "fi",
    "codepoint": 64257,
    "rows": [
      "..##.#",
      ".#....",
      "###.##",
      ".#...#",
      ".#...#",
      ".#...#",
      ".#...#"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 7,
    "source": "derived — the strike's f and i, joined at f's own advance"
  },
  {
    "face": "VF Body",
    "char": "ﬂ",
    "name": "fl",
    "codepoint": 64258,
    "rows": [
      "..####",
      ".#...#",
      "###..#",
      ".#...#",
      ".#...#",
      ".#...#",
      ".#...#"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 7,
    "source": "derived — the strike's f and l, joined at f's own advance"
  },
  {
    "face": "VF Body",
    "char": "Á",
    "name": "Aacute",
    "codepoint": 193,
    "rows": [
      "...#.",
      "..#..",
      ".....",
      "..#..",
      "..#..",
      ".#.#.",
      ".#.#.",
      "#####",
      "#...#",
      "#...#"
    ],
    "x0": 1,
    "y0": 0,
    "advance": 7,
    "source": "composed — the strike's A under its own acute"
  },
  {
    "face": "VF Body",
    "char": "Â",
    "name": "Acircumflex",
    "codepoint": 194,
    "rows": [
      "..#..",
      ".#.#.",
      ".....",
      "..#..",
      "..#..",
      ".#.#.",
      ".#.#.",
      "#####",
      "#...#",
      "#...#"
    ],
    "x0": 1,
    "y0": 0,
    "advance": 7,
    "source": "composed — the strike's A under its own circumflex"
  },
  {
    "face": "VF Body",
    "char": "È",
    "name": "Egrave",
    "codepoint": 200,
    "rows": [
      ".#..",
      "..#.",
      "....",
      "####",
      "#...",
      "#...",
      "###.",
      "#...",
      "#...",
      "####"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 5,
    "source": "composed — the strike's E under its own grave (its É, mirrored)"
  },
  {
    "face": "VF Body",
    "char": "Ê",
    "name": "Ecircumflex",
    "codepoint": 202,
    "rows": [
      ".#..",
      "#.#.",
      "....",
      "####",
      "#...",
      "#...",
      "###.",
      "#...",
      "#...",
      "####"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 5,
    "source": "composed — the strike's E under its own circumflex (placed as its ê)"
  },
  {
    "face": "VF Body",
    "char": "Ë",
    "name": "Edieresis",
    "codepoint": 203,
    "rows": [
      "#..#",
      "....",
      "####",
      "#...",
      "#...",
      "###.",
      "#...",
      "#...",
      "####"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 5,
    "source": "composed — the strike's E under its own dieresis (dots over the stems, as its ë)"
  },
  {
    "face": "VF Body",
    "char": "Ì",
    "name": "Igrave",
    "codepoint": 204,
    "rows": [
      "#.",
      ".#",
      "..",
      ".#",
      ".#",
      ".#",
      ".#",
      ".#",
      ".#",
      ".#"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 3,
    "source": "composed — the strike's I under its own grave (accent left of the stem, as its ì)"
  },
  {
    "face": "VF Body",
    "char": "Í",
    "name": "Iacute",
    "codepoint": 205,
    "rows": [
      ".#",
      "#.",
      "..",
      ".#",
      ".#",
      ".#",
      ".#",
      ".#",
      ".#",
      ".#"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 3,
    "source": "composed — the strike's I under its own acute (as its í)"
  },
  {
    "face": "VF Body",
    "char": "Î",
    "name": "Icircumflex",
    "codepoint": 206,
    "rows": [
      ".#.",
      "#.#",
      "...",
      ".#.",
      ".#.",
      ".#.",
      ".#.",
      ".#.",
      ".#.",
      ".#."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 4,
    "source": "composed — the strike's I under its own circumflex (as its î; a wider letter, like î vs í)"
  },
  {
    "face": "VF Body",
    "char": "Ï",
    "name": "Idieresis",
    "codepoint": 207,
    "rows": [
      "#.#",
      "...",
      ".#.",
      ".#.",
      ".#.",
      ".#.",
      ".#.",
      ".#.",
      ".#."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 4,
    "source": "composed — the strike's I under its own dieresis (as its ï)"
  },
  {
    "face": "VF Body",
    "char": "Ò",
    "name": "Ograve",
    "codepoint": 210,
    "rows": [
      ".#...",
      "..#..",
      ".....",
      ".###.",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      ".###."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 6,
    "source": "composed — the strike's O under its own grave"
  },
  {
    "face": "VF Body",
    "char": "Ó",
    "name": "Oacute",
    "codepoint": 211,
    "rows": [
      "...#.",
      "..#..",
      ".....",
      ".###.",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      ".###."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 6,
    "source": "composed — the strike's O under its own acute"
  },
  {
    "face": "VF Body",
    "char": "Ô",
    "name": "Ocircumflex",
    "codepoint": 212,
    "rows": [
      "..#..",
      ".#.#.",
      ".....",
      ".###.",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      ".###."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 6,
    "source": "composed — the strike's O under its own circumflex"
  },
  {
    "face": "VF Body",
    "char": "Ù",
    "name": "Ugrave",
    "codepoint": 217,
    "rows": [
      ".#...",
      "..#..",
      ".....",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      ".###."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 6,
    "source": "composed — the strike's U under its own grave"
  },
  {
    "face": "VF Body",
    "char": "Ú",
    "name": "Uacute",
    "codepoint": 218,
    "rows": [
      "...#.",
      "..#..",
      ".....",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      ".###."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 6,
    "source": "composed — the strike's U under its own acute"
  },
  {
    "face": "VF Body",
    "char": "Û",
    "name": "Ucircumflex",
    "codepoint": 219,
    "rows": [
      "..#..",
      ".#.#.",
      ".....",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      ".###."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 6,
    "source": "composed — the strike's U under its own circumflex"
  },
  {
    "face": "VF Body",
    "char": "←",
    "name": "arrowleft",
    "codepoint": 8592,
    "rows": [
      "..#....",
      ".#.....",
      "#######",
      ".#.....",
      "..#...."
    ],
    "x0": 0,
    "y0": 1,
    "advance": 8,
    "source": "drawn — chevron-headed arrow on the math axis"
  },
  {
    "face": "VF Body",
    "char": "→",
    "name": "arrowright",
    "codepoint": 8594,
    "rows": [
      "....#..",
      ".....#.",
      "#######",
      ".....#.",
      "....#.."
    ],
    "x0": 0,
    "y0": 1,
    "advance": 8,
    "source": "drawn — chevron-headed arrow on the math axis"
  },
  {
    "face": "VF Body",
    "char": "↑",
    "name": "arrowup",
    "codepoint": 8593,
    "rows": [
      "..#..",
      ".#.#.",
      "#.#.#",
      "..#..",
      "..#..",
      "..#..",
      "..#.."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 6,
    "source": "drawn — chevron-headed arrow, cap height"
  },
  {
    "face": "VF Body",
    "char": "↓",
    "name": "arrowdown",
    "codepoint": 8595,
    "rows": [
      "..#..",
      "..#..",
      "..#..",
      "..#..",
      "#.#.#",
      ".#.#.",
      "..#.."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 6,
    "source": "drawn — chevron-headed arrow, cap height"
  },
  {
    "face": "VF Body",
    "char": "✕",
    "name": "multiplicationx",
    "codepoint": 10005,
    "rows": [
      "#.....#",
      ".#...#.",
      "..#.#..",
      "...#...",
      "..#.#..",
      ".#...#.",
      "#.....#"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 8,
    "source": "drawn — the ballot X: the × saltire at full cap size"
  },
  {
    "face": "VF Body",
    "char": "★",
    "name": "blackstar",
    "codepoint": 9733,
    "rows": [
      "...#...",
      "..###..",
      "#######",
      ".#####.",
      "..###..",
      ".##.##.",
      ".#...#."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 8,
    "source": "drawn — a five-point star filled solid, cap size (Adam's ink, 2026-08-09)"
  },
  {
    "face": "VF Body",
    "char": "⇧",
    "name": "shift",
    "codepoint": 8679,
    "rows": [
      "....#....",
      "...#.#...",
      "..#...#..",
      ".#.....#.",
      "##.....##",
      "..#...#..",
      "..#...#..",
      "..#...#..",
      "..#####.."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 10,
    "source": "drawn — the shift key outline (Adam's ink, 2026-08-09)"
  },
  {
    "face": "VF Body",
    "char": "⌥",
    "name": "option",
    "codepoint": 8997,
    "rows": [
      "##..###",
      "..#....",
      "...#...",
      "....#..",
      ".....##"
    ],
    "x0": 0,
    "y0": 1,
    "advance": 8,
    "source": "drawn — the option key switch"
  },
  {
    "face": "VF Body",
    "char": "⌃",
    "name": "control",
    "codepoint": 8963,
    "rows": [
      "..#..",
      ".#.#.",
      "#...#"
    ],
    "x0": 0,
    "y0": 3,
    "advance": 6,
    "source": "drawn — the control chevron, in the cap's upper band"
  }
]
