// GENERATED by fonts/add-glyphs.py — do not edit. Every glyph the
// kit adds to the shipped faces, with its bitmap (top row first,
// '#' = ink), placement in design px (y0 = bottom edge, baseline 0)
// and provenance. Rendered by glyph-proof.html.
export interface BackfillGlyph {
  face: string
  char: string
  name: string
  codepoint: number
  rows: string[]
  x0: number
  y0: number
  advance: number
  source: string
}

export const BACKFILL_GLYPHS: BackfillGlyph[] = [
  {
    "face": "VF Display",
    "char": "×",
    "name": "multiply",
    "codepoint": 215,
    "rows": [
      "#...#",
      ".#.#.",
      "..#..",
      ".#.#.",
      "#...#"
    ],
    "x0": 1,
    "y0": 2,
    "advance": 7,
    "source": "drawn — the saltire in the strike's own + box, on the math axis"
  },
  {
    "face": "VF Display",
    "char": "⁄",
    "name": "fraction",
    "codepoint": 8260,
    "rows": [
      "....#",
      "....#",
      "...#.",
      "...#.",
      "..#..",
      "..#..",
      ".#...",
      ".#...",
      "#....",
      "#...."
    ],
    "x0": 1,
    "y0": 0,
    "advance": 7,
    "source": "traced — the strike's /, verbatim (replaces the slot's ✓ ink; ✓ stays at U+2713)"
  },
  {
    "face": "VF Display",
    "char": "€",
    "name": "currency",
    "codepoint": 8364,
    "rows": [
      ".####.",
      "##....",
      "##....",
      "######",
      "##....",
      "######",
      "##....",
      "##....",
      ".####."
    ],
    "x0": 1,
    "y0": 0,
    "advance": 8,
    "source": "drawn — the strike's own C, curve left open, crossed by two full-width bars (replaces the slot's ◆ ink; ◆ stays at U+25C6)"
  },
  {
    "face": "VF Display",
    "char": "‹",
    "name": "guilsinglleft",
    "codepoint": 8249,
    "rows": [
      "...#",
      "..#.",
      ".#..",
      "#...",
      ".#..",
      "..#.",
      "...#"
    ],
    "x0": 1,
    "y0": 0,
    "advance": 6,
    "source": "derived — one chevron of the strike's « (replaces the slot's  ink;  stays at U+F8FF)"
  },
  {
    "face": "VF Display",
    "char": "›",
    "name": "guilsinglright",
    "codepoint": 8250,
    "rows": [
      "#...",
      ".#..",
      "..#.",
      "...#",
      "..#.",
      ".#..",
      "#..."
    ],
    "x0": 1,
    "y0": 0,
    "advance": 6,
    "source": "derived — one chevron of the strike's » (the slot was empty)"
  },
  {
    "face": "VF Display",
    "char": "−",
    "name": "minus",
    "codepoint": 8722,
    "rows": [
      "#####"
    ],
    "x0": 1,
    "y0": 4,
    "advance": 7,
    "source": "traced — the strike's hyphen, verbatim (already the width of its + crossbar)"
  },
  {
    "face": "VF Display",
    "char": "·",
    "name": "periodcentered",
    "codepoint": 183,
    "rows": [
      "##",
      "##"
    ],
    "x0": 1,
    "y0": 4,
    "advance": 4,
    "source": "derived — the strike's 2x2 period dot raised to the math axis"
  },
  {
    "face": "VF Display",
    "char": "¹",
    "name": "onesuperior",
    "codepoint": 185,
    "rows": [
      ".#",
      "##",
      ".#",
      ".#",
      ".#"
    ],
    "x0": 1,
    "y0": 4,
    "advance": 4,
    "source": "drawn — a 2x5 digit at superscript height (top at cap height)"
  },
  {
    "face": "VF Display",
    "char": "²",
    "name": "twosuperior",
    "codepoint": 178,
    "rows": [
      "##.",
      "..#",
      ".#.",
      "#..",
      "###"
    ],
    "x0": 1,
    "y0": 4,
    "advance": 5,
    "source": "drawn — a 3x5 digit at superscript height"
  },
  {
    "face": "VF Display",
    "char": "³",
    "name": "threesuperior",
    "codepoint": 179,
    "rows": [
      "##.",
      "..#",
      ".#.",
      "..#",
      "##."
    ],
    "x0": 1,
    "y0": 4,
    "advance": 5,
    "source": "drawn — a 3x5 digit at superscript height"
  },
  {
    "face": "VF Display",
    "char": "½",
    "name": "onehalf",
    "codepoint": 189,
    "rows": [
      ".#.......",
      "##...#...",
      ".#...#...",
      ".#..#....",
      "....#.##.",
      "...#....#",
      "...#...#.",
      "......###"
    ],
    "x0": 1,
    "y0": 0,
    "advance": 11,
    "source": "drawn — the body face's ½, on Chicago's bearings (1px minis match its 1px /)"
  },
  {
    "face": "VF Display",
    "char": "¼",
    "name": "onequarter",
    "codepoint": 188,
    "rows": [
      ".#.......",
      "##...#...",
      ".#...#...",
      ".#..#....",
      "....#.#.#",
      "...#..#.#",
      "...#..###",
      "........#"
    ],
    "x0": 1,
    "y0": 0,
    "advance": 11,
    "source": "drawn — the body face's ¼, on Chicago's bearings"
  },
  {
    "face": "VF Display",
    "char": "¾",
    "name": "threequarters",
    "codepoint": 190,
    "rows": [
      "##.......",
      "..#..#...",
      ".#...#...",
      "..#.#....",
      "##..#.#.#",
      "...#..#.#",
      "...#..###",
      "........#"
    ],
    "x0": 1,
    "y0": 0,
    "advance": 11,
    "source": "drawn — the body face's ¾, on Chicago's bearings"
  },
  {
    "face": "VF Display",
    "char": "′",
    "name": "prime",
    "codepoint": 8242,
    "rows": [
      "##",
      "##",
      ".#",
      "#."
    ],
    "x0": 1,
    "y0": 4,
    "advance": 4,
    "source": "derived — the strike's ’ ink, dropped to sit on the x-height band"
  },
  {
    "face": "VF Display",
    "char": "″",
    "name": "doubleprime",
    "codepoint": 8243,
    "rows": [
      "##.##",
      "##.##",
      ".#..#",
      "#..#."
    ],
    "x0": 1,
    "y0": 4,
    "advance": 7,
    "source": "derived — two of the strike's ’ ink, one gap apart"
  },
  {
    "face": "VF Display",
    "char": "‚",
    "name": "quotesinglbase",
    "codepoint": 8218,
    "rows": [
      "##",
      "##",
      ".#",
      "#."
    ],
    "x0": 1,
    "y0": -2,
    "advance": 4,
    "source": "traced — the strike's comma, verbatim (a low-9 quote is a comma)"
  },
  {
    "face": "VF Display",
    "char": "„",
    "name": "quotedblbase",
    "codepoint": 8222,
    "rows": [
      "##.##",
      "##.##",
      ".#..#",
      "#..#."
    ],
    "x0": 1,
    "y0": -2,
    "advance": 7,
    "source": "derived — the strike's comma, doubled one gap apart"
  },
  {
    "face": "VF Display",
    "char": "‡",
    "name": "daggerdbl",
    "codepoint": 8225,
    "rows": [
      ".#.",
      "###",
      ".#.",
      ".#.",
      "###",
      ".#."
    ],
    "x0": 1,
    "y0": 3,
    "advance": 5,
    "source": "derived — the strike's † with its own crossbar repeated below"
  },
  {
    "face": "VF Display",
    "char": "‰",
    "name": "perthousand",
    "codepoint": 8240,
    "rows": [
      ".##.###.....",
      "#..#..#.....",
      "#..#.#......",
      ".##..#......",
      "....#.......",
      "....#.......",
      "...#..##.##.",
      "...#.#..#..#",
      "..#..#..#..#",
      "..#...##.##."
    ],
    "x0": 1,
    "y0": 0,
    "advance": 14,
    "source": "derived — the strike's % with its lower loop doubled into a shared-wall 00 (Adam's motif)"
  },
  {
    "face": "VF Display",
    "char": "ﬁ",
    "name": "fi",
    "codepoint": 64257,
    "rows": [
      "..###.##",
      ".##.....",
      "####..##",
      ".##...##",
      ".##...##",
      ".##...##",
      ".##...##",
      ".##...##",
      ".##...##"
    ],
    "x0": 1,
    "y0": 0,
    "advance": 10,
    "source": "derived — the strike's f and i, joined at f's own advance"
  },
  {
    "face": "VF Display",
    "char": "ﬂ",
    "name": "fl",
    "codepoint": 64258,
    "rows": [
      "..###.##",
      ".##...##",
      "####..##",
      ".##...##",
      ".##...##",
      ".##...##",
      ".##...##",
      ".##...##",
      ".##...##"
    ],
    "x0": 1,
    "y0": 0,
    "advance": 10,
    "source": "derived — the strike's f and l, joined at f's own advance"
  },
  {
    "face": "VF Display",
    "char": "Á",
    "name": "Aacute",
    "codepoint": 193,
    "rows": [
      "...#..",
      "..#...",
      "......",
      ".####.",
      "##..##",
      "##..##",
      "##..##",
      "######",
      "##..##",
      "##..##",
      "##..##",
      "##..##"
    ],
    "x0": 1,
    "y0": 0,
    "advance": 8,
    "source": "composed — the strike's A under its own acute"
  },
  {
    "face": "VF Display",
    "char": "Â",
    "name": "Acircumflex",
    "codepoint": 194,
    "rows": [
      "..##..",
      ".#..#.",
      "......",
      ".####.",
      "##..##",
      "##..##",
      "##..##",
      "######",
      "##..##",
      "##..##",
      "##..##",
      "##..##"
    ],
    "x0": 1,
    "y0": 0,
    "advance": 8,
    "source": "composed — the strike's A under its own circumflex"
  },
  {
    "face": "VF Display",
    "char": "È",
    "name": "Egrave",
    "codepoint": 200,
    "rows": [
      ".#...",
      "..#..",
      ".....",
      "#####",
      "##...",
      "##...",
      "##...",
      "####.",
      "##...",
      "##...",
      "##...",
      "#####"
    ],
    "x0": 1,
    "y0": 0,
    "advance": 7,
    "source": "composed — the strike's E under its own grave (its É, mirrored)"
  },
  {
    "face": "VF Display",
    "char": "Ê",
    "name": "Ecircumflex",
    "codepoint": 202,
    "rows": [
      ".##..",
      "#..#.",
      ".....",
      "#####",
      "##...",
      "##...",
      "##...",
      "####.",
      "##...",
      "##...",
      "##...",
      "#####"
    ],
    "x0": 1,
    "y0": 0,
    "advance": 7,
    "source": "composed — the strike's E under its own circumflex"
  },
  {
    "face": "VF Display",
    "char": "Ë",
    "name": "Edieresis",
    "codepoint": 203,
    "rows": [
      ".#..#",
      ".....",
      "#####",
      "##...",
      "##...",
      "##...",
      "####.",
      "##...",
      "##...",
      "##...",
      "#####"
    ],
    "x0": 1,
    "y0": 0,
    "advance": 7,
    "source": "composed — the strike's E under its own dieresis"
  },
  {
    "face": "VF Display",
    "char": "Ì",
    "name": "Igrave",
    "codepoint": 204,
    "rows": [
      "#.",
      ".#",
      "..",
      "##",
      "##",
      "##",
      "##",
      "##",
      "##",
      "##",
      "##",
      "##"
    ],
    "x0": 2,
    "y0": 0,
    "advance": 6,
    "source": "composed — the strike's I under its own grave (as its ì)"
  },
  {
    "face": "VF Display",
    "char": "Í",
    "name": "Iacute",
    "codepoint": 205,
    "rows": [
      ".#",
      "#.",
      "..",
      "##",
      "##",
      "##",
      "##",
      "##",
      "##",
      "##",
      "##",
      "##"
    ],
    "x0": 2,
    "y0": 0,
    "advance": 6,
    "source": "composed — the strike's I under its own acute (as its í)"
  },
  {
    "face": "VF Display",
    "char": "Î",
    "name": "Icircumflex",
    "codepoint": 206,
    "rows": [
      ".##.",
      "#..#",
      "....",
      ".##.",
      ".##.",
      ".##.",
      ".##.",
      ".##.",
      ".##.",
      ".##.",
      ".##.",
      ".##."
    ],
    "x0": 1,
    "y0": 0,
    "advance": 6,
    "source": "composed — the strike's I under its own circumflex (as its î)"
  },
  {
    "face": "VF Display",
    "char": "Ï",
    "name": "Idieresis",
    "codepoint": 207,
    "rows": [
      "#..#",
      "....",
      ".##.",
      ".##.",
      ".##.",
      ".##.",
      ".##.",
      ".##.",
      ".##.",
      ".##.",
      ".##."
    ],
    "x0": 1,
    "y0": 0,
    "advance": 6,
    "source": "composed — the strike's I under its own dieresis (as its ï)"
  },
  {
    "face": "VF Display",
    "char": "Ò",
    "name": "Ograve",
    "codepoint": 210,
    "rows": [
      "..#...",
      "...#..",
      "......",
      ".####.",
      "##..##",
      "##..##",
      "##..##",
      "##..##",
      "##..##",
      "##..##",
      "##..##",
      ".####."
    ],
    "x0": 1,
    "y0": 0,
    "advance": 8,
    "source": "composed — the strike's O under its own grave"
  },
  {
    "face": "VF Display",
    "char": "Ó",
    "name": "Oacute",
    "codepoint": 211,
    "rows": [
      "...#..",
      "..#...",
      "......",
      ".####.",
      "##..##",
      "##..##",
      "##..##",
      "##..##",
      "##..##",
      "##..##",
      "##..##",
      ".####."
    ],
    "x0": 1,
    "y0": 0,
    "advance": 8,
    "source": "composed — the strike's O under its own acute"
  },
  {
    "face": "VF Display",
    "char": "Ô",
    "name": "Ocircumflex",
    "codepoint": 212,
    "rows": [
      "..##..",
      ".#..#.",
      "......",
      ".####.",
      "##..##",
      "##..##",
      "##..##",
      "##..##",
      "##..##",
      "##..##",
      "##..##",
      ".####."
    ],
    "x0": 1,
    "y0": 0,
    "advance": 8,
    "source": "composed — the strike's O under its own circumflex"
  },
  {
    "face": "VF Display",
    "char": "Ù",
    "name": "Ugrave",
    "codepoint": 217,
    "rows": [
      "..#...",
      "...#..",
      "......",
      "##..##",
      "##..##",
      "##..##",
      "##..##",
      "##..##",
      "##..##",
      "##..##",
      "##..##",
      ".####."
    ],
    "x0": 1,
    "y0": 0,
    "advance": 8,
    "source": "composed — the strike's U under its own grave"
  },
  {
    "face": "VF Display",
    "char": "Ú",
    "name": "Uacute",
    "codepoint": 218,
    "rows": [
      "...#..",
      "..#...",
      "......",
      "##..##",
      "##..##",
      "##..##",
      "##..##",
      "##..##",
      "##..##",
      "##..##",
      "##..##",
      ".####."
    ],
    "x0": 1,
    "y0": 0,
    "advance": 8,
    "source": "composed — the strike's U under its own acute"
  },
  {
    "face": "VF Display",
    "char": "Û",
    "name": "Ucircumflex",
    "codepoint": 219,
    "rows": [
      "..##..",
      ".#..#.",
      "......",
      "##..##",
      "##..##",
      "##..##",
      "##..##",
      "##..##",
      "##..##",
      "##..##",
      "##..##",
      ".####."
    ],
    "x0": 1,
    "y0": 0,
    "advance": 8,
    "source": "composed — the strike's U under its own circumflex"
  },
  {
    "face": "VF Display",
    "char": "←",
    "name": "arrowleft",
    "codepoint": 8592,
    "rows": [
      "..#......",
      ".##......",
      "#########",
      "#########",
      ".##......",
      "..#......"
    ],
    "x0": 1,
    "y0": 2,
    "advance": 11,
    "source": "drawn — 2px-shaft arrow on the math axis"
  },
  {
    "face": "VF Display",
    "char": "→",
    "name": "arrowright",
    "codepoint": 8594,
    "rows": [
      "......#..",
      "......##.",
      "#########",
      "#########",
      "......##.",
      "......#.."
    ],
    "x0": 1,
    "y0": 2,
    "advance": 11,
    "source": "drawn — 2px-shaft arrow on the math axis"
  },
  {
    "face": "VF Display",
    "char": "↑",
    "name": "arrowup",
    "codepoint": 8593,
    "rows": [
      "...##...",
      "..####..",
      ".######.",
      "...##...",
      "...##...",
      "...##...",
      "...##...",
      "...##...",
      "...##..."
    ],
    "x0": 1,
    "y0": 0,
    "advance": 10,
    "source": "drawn — 2px-stem arrow, cap height"
  },
  {
    "face": "VF Display",
    "char": "↓",
    "name": "arrowdown",
    "codepoint": 8595,
    "rows": [
      "...##...",
      "...##...",
      "...##...",
      "...##...",
      "...##...",
      "...##...",
      ".######.",
      "..####..",
      "...##..."
    ],
    "x0": 1,
    "y0": 0,
    "advance": 10,
    "source": "drawn — 2px-stem arrow, cap height"
  },
  {
    "face": "VF Display",
    "char": "✕",
    "name": "multiplicationx",
    "codepoint": 10005,
    "rows": [
      "##....##",
      ".##..##.",
      "..####..",
      "...##...",
      "..####..",
      ".##..##.",
      "##....##"
    ],
    "x0": 1,
    "y0": 1,
    "advance": 10,
    "source": "drawn — the ballot X at the strike's 2px stroke"
  },
  {
    "face": "VF Display",
    "char": "★",
    "name": "blackstar",
    "codepoint": 9733,
    "rows": [
      "....#....",
      "...###...",
      "...###...",
      "#########",
      ".#######.",
      "..#####..",
      "..#####..",
      ".###.###.",
      ".#.....#."
    ],
    "x0": 1,
    "y0": 0,
    "advance": 11,
    "source": "drawn — the five-point star at the 9px cap band (Adam's ink, 2026-08-09)"
  },
  {
    "face": "VF Display",
    "char": "☆",
    "name": "whitestar",
    "codepoint": 9734,
    "rows": [
      "....#....",
      "...#.#...",
      "...#.#...",
      "###...###",
      ".#.....#.",
      "..#...#..",
      "..#.#.#..",
      ".###.###.",
      ".#.....#."
    ],
    "x0": 1,
    "y0": 0,
    "advance": 11,
    "source": "drawn — the same star as an outline ring, hollow interior (Adam's ink, 2026-08-09)"
  },
  {
    "face": "VF Display",
    "char": "⇧",
    "name": "shift",
    "codepoint": 8679,
    "rows": [
      "....#....",
      "...#.#...",
      "..#...#..",
      ".#.....#.",
      "##.....##",
      "..#...#..",
      "..#...#..",
      "..#...#..",
      "..#####.."
    ],
    "x0": 1,
    "y0": 0,
    "advance": 11,
    "source": "drawn — the shift key outline (Adam's ink), the same 9x9 box as the strike's ⌘"
  },
  {
    "face": "VF Display",
    "char": "⌥",
    "name": "option",
    "codepoint": 8997,
    "rows": [
      "##..###",
      "..#....",
      "...#...",
      "....#..",
      ".....##"
    ],
    "x0": 1,
    "y0": 2,
    "advance": 9,
    "source": "drawn — the option key switch"
  },
  {
    "face": "VF Display",
    "char": "⌃",
    "name": "control",
    "codepoint": 8963,
    "rows": [
      "..#..",
      ".#.#.",
      "#...#"
    ],
    "x0": 1,
    "y0": 5,
    "advance": 7,
    "source": "drawn — the control chevron, in the cap's upper band"
  },
  {
    "face": "VF Display",
    "char": "⎋",
    "name": "escape",
    "codepoint": 9099,
    "rows": [
      "###.....",
      "##..##..",
      "#.#...#.",
      "...#...#",
      ".#.....#",
      ".#.....#",
      "..#...#.",
      "...###.."
    ],
    "x0": 1,
    "y0": 0,
    "advance": 10,
    "source": "drawn — the escape key: the arrow's shaft doubling as the ring's top-left arc (Adam's ink, 2026-08-10)"
  },
  {
    "face": "VF Display",
    "char": "⌫",
    "name": "deleteleft",
    "codepoint": 9003,
    "rows": [
      "...########",
      "..#.......#",
      ".#...#.#..#",
      "#.....#...#",
      ".#...#.#..#",
      "..#.......#",
      "...########"
    ],
    "x0": 1,
    "y0": 1,
    "advance": 13,
    "source": "drawn — the delete-back eraser pentagon around a 3x3 saltire"
  },
  {
    "face": "VF Display",
    "char": "⏎",
    "name": "returnsymbol",
    "codepoint": 9166,
    "rows": [
      "........#",
      "........#",
      "..#.....#",
      ".#......#",
      "#########",
      ".#.......",
      "..#......"
    ],
    "x0": 1,
    "y0": 1,
    "advance": 11,
    "source": "drawn — the return symbol, its head the text arrows' own chevron"
  },
  {
    "face": "VF Display",
    "char": "⇥",
    "name": "tabright",
    "codepoint": 8677,
    "rows": [
      "........#",
      "....#...#",
      ".....#..#",
      "#######.#",
      ".....#..#",
      "....#...#",
      "........#"
    ],
    "x0": 1,
    "y0": 1,
    "advance": 11,
    "source": "drawn — tab: the text arrow stopped by a bar"
  },
  {
    "face": "VF Display",
    "char": "⇤",
    "name": "tableft",
    "codepoint": 8676,
    "rows": [
      "#........",
      "#...#....",
      "#..#.....",
      "#.#######",
      "#..#.....",
      "#...#....",
      "#........"
    ],
    "x0": 1,
    "y0": 1,
    "advance": 11,
    "source": "drawn — back-tab, the ⇥'s mirror"
  },
  {
    "face": "VF Display",
    "char": "↩",
    "name": "hookarrowleft",
    "codepoint": 8617,
    "rows": [
      ".....###.",
      "........#",
      "..#.....#",
      ".#......#",
      "#########",
      ".#.......",
      "..#......"
    ],
    "x0": 1,
    "y0": 1,
    "advance": 11,
    "source": "drawn — the ⏎ with its tail curled instead of squared"
  },
  {
    "face": "VF Display",
    "char": "●",
    "name": "blackcircle",
    "codepoint": 9679,
    "rows": [
      "..###..",
      ".#####.",
      "#######",
      "#######",
      "#######",
      ".#####.",
      "..###.."
    ],
    "x0": 1,
    "y0": 1,
    "advance": 9,
    "source": "drawn — the strike's • disc grown to its ◆'s 7x7 cell and advance"
  },
  {
    "face": "VF Display",
    "char": "○",
    "name": "whitecircle",
    "codepoint": 9675,
    "rows": [
      "..###..",
      ".#...#.",
      "#.....#",
      "#.....#",
      "#.....#",
      ".#...#.",
      "..###.."
    ],
    "x0": 1,
    "y0": 1,
    "advance": 9,
    "source": "drawn — the ● as a 1px ring, the ⌘'s stroke"
  },
  {
    "face": "VF Display",
    "char": "■",
    "name": "blacksquare",
    "codepoint": 9632,
    "rows": [
      "#######",
      "#######",
      "#######",
      "#######",
      "#######",
      "#######",
      "#######"
    ],
    "x0": 1,
    "y0": 1,
    "advance": 9,
    "source": "drawn — the ◆'s 7x7 cell filled solid"
  },
  {
    "face": "VF Display",
    "char": "□",
    "name": "whitesquare",
    "codepoint": 9633,
    "rows": [
      "#######",
      "#.....#",
      "#.....#",
      "#.....#",
      "#.....#",
      "#.....#",
      "#######"
    ],
    "x0": 1,
    "y0": 1,
    "advance": 9,
    "source": "drawn — the ■ as a 1px ring"
  },
  {
    "face": "VF Display",
    "char": "◦",
    "name": "whitebullet",
    "codepoint": 9702,
    "rows": [
      ".###.",
      "#...#",
      "#...#",
      "#...#",
      ".###."
    ],
    "x0": 1,
    "y0": 2,
    "advance": 7,
    "source": "derived — the strike's own • hollowed to a ring, in its exact box and advance"
  },
  {
    "face": "VF Display",
    "char": "✗",
    "name": "ballotx",
    "codepoint": 10007,
    "rows": [
      "##....##",
      ".##..##.",
      "..####..",
      "...##...",
      "..####..",
      ".##..##.",
      "##....##"
    ],
    "x0": 1,
    "y0": 1,
    "advance": 10,
    "source": "traced — the face's own ✕ (at strike sizes one X serves both codepoints)"
  },
  {
    "face": "VF Display",
    "char": "▸",
    "name": "smalltriangleright",
    "codepoint": 9656,
    "rows": [
      "#...",
      "##..",
      "###.",
      "####",
      "###.",
      "##..",
      "#..."
    ],
    "x0": 1,
    "y0": 1,
    "advance": 6,
    "source": "derived — the right half of the strike's own ◆ (the submenu wedge)"
  },
  {
    "face": "VF Display",
    "char": "◂",
    "name": "smalltriangleleft",
    "codepoint": 9666,
    "rows": [
      "...#",
      "..##",
      ".###",
      "####",
      ".###",
      "..##",
      "...#"
    ],
    "x0": 1,
    "y0": 1,
    "advance": 6,
    "source": "derived — the left half of the strike's own ◆"
  },
  {
    "face": "VF Display",
    "char": "▴",
    "name": "smalltriangleup",
    "codepoint": 9652,
    "rows": [
      "...#...",
      "..###..",
      ".#####.",
      "#######"
    ],
    "x0": 1,
    "y0": 2,
    "advance": 9,
    "source": "derived — the top half of the strike's own ◆"
  },
  {
    "face": "VF Display",
    "char": "▾",
    "name": "smalltriangledown",
    "codepoint": 9662,
    "rows": [
      "#######",
      ".#####.",
      "..###..",
      "...#..."
    ],
    "x0": 1,
    "y0": 2,
    "advance": 9,
    "source": "derived — the bottom half of the strike's own ◆"
  },
  {
    "face": "VF Display",
    "char": "▶",
    "name": "triangleright",
    "codepoint": 9654,
    "rows": [
      "#....",
      "##...",
      "###..",
      "####.",
      "#####",
      "####.",
      "###..",
      "##...",
      "#...."
    ],
    "x0": 1,
    "y0": 0,
    "advance": 7,
    "source": "drawn — the ▸ wedge grown to the 9px cap band"
  },
  {
    "face": "VF Display",
    "char": "◀",
    "name": "triangleleft",
    "codepoint": 9664,
    "rows": [
      "....#",
      "...##",
      "..###",
      ".####",
      "#####",
      ".####",
      "..###",
      "...##",
      "....#"
    ],
    "x0": 1,
    "y0": 0,
    "advance": 7,
    "source": "drawn — the ▶'s mirror"
  },
  {
    "face": "VF Display",
    "char": "‑",
    "name": "nonbreakinghyphen",
    "codepoint": 8209,
    "rows": [
      "#####"
    ],
    "x0": 1,
    "y0": 4,
    "advance": 7,
    "source": "traced — the strike's hyphen, verbatim (the hyphen that refuses the break)"
  },
  {
    "face": "VF Display",
    "char": "­",
    "name": "softhyphen",
    "codepoint": 173,
    "rows": [
      "#####"
    ],
    "x0": 1,
    "y0": 4,
    "advance": 7,
    "source": "traced — the strike's hyphen, verbatim (visible only where a line breaks)"
  },
  {
    "face": "VF Display",
    "char": " ",
    "name": "figurespace",
    "codepoint": 8199,
    "rows": [
      "........"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 8,
    "source": "derived — no ink: the strike's own 8px digit advance, so numerals stay columnar"
  },
  {
    "face": "VF Display",
    "char": " ",
    "name": "thinspace",
    "codepoint": 8201,
    "rows": [
      ".."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 2,
    "source": "derived — no ink: 2px, two under the strike's 4px word space"
  },
  {
    "face": "VF Display",
    "char": " ",
    "name": "hairspace",
    "codepoint": 8202,
    "rows": [
      "."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 1,
    "source": "derived — no ink: the 1px minimum the pixel grid can state"
  },
  {
    "face": "VF Body",
    "char": "×",
    "name": "multiply",
    "codepoint": 215,
    "rows": [
      "#...#",
      ".#.#.",
      "..#..",
      ".#.#.",
      "#...#"
    ],
    "x0": 0,
    "y0": 1,
    "advance": 6,
    "source": "drawn — the saltire in the strike's own + box, on the math axis"
  },
  {
    "face": "VF Body",
    "char": "⌘",
    "name": "command",
    "codepoint": 8984,
    "rows": [
      ".##...##.",
      "#..#.#..#",
      "#..#.#..#",
      ".#######.",
      "...#.#...",
      ".#######.",
      "#..#.#..#",
      "#..#.#..#",
      ".##...##."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 10,
    "source": "traced — Chicago's ⌘, verbatim, on Geneva's flush-left spacing"
  },
  {
    "face": "VF Body",
    "char": "✓",
    "name": "checkmark",
    "codepoint": 10003,
    "rows": [
      "........#",
      ".......##",
      "......##.",
      ".....##..",
      "#...##...",
      "##.##....",
      ".###.....",
      "..#......"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 10,
    "source": "traced — Chicago's ✓, verbatim, on Geneva's flush-left spacing"
  },
  {
    "face": "VF Body",
    "char": "€",
    "name": "euro",
    "codepoint": 8364,
    "rows": [
      ".###.",
      "#....",
      "#####",
      "#....",
      "#####",
      "#....",
      ".###."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 6,
    "source": "drawn — the strike's own C, curve left open (its corner stubs dropped), crossed by two full-width bars (the € postdates every source strike)"
  },
  {
    "face": "VF Body",
    "char": "−",
    "name": "minus",
    "codepoint": 8722,
    "rows": [
      "#####"
    ],
    "x0": 0,
    "y0": 3,
    "advance": 6,
    "source": "derived — the crossbar of the strike's own +, alone on the math axis"
  },
  {
    "face": "VF Body",
    "char": "·",
    "name": "periodcentered",
    "codepoint": 183,
    "rows": [
      "#"
    ],
    "x0": 1,
    "y0": 3,
    "advance": 3,
    "source": "derived — the strike's period dot raised to the math axis, its bearing kept"
  },
  {
    "face": "VF Body",
    "char": "¹",
    "name": "onesuperior",
    "codepoint": 185,
    "rows": [
      ".#",
      "##",
      ".#",
      ".#",
      ".#"
    ],
    "x0": 0,
    "y0": 2,
    "advance": 3,
    "source": "drawn — a 2x5 digit at superscript height (top at cap height)"
  },
  {
    "face": "VF Body",
    "char": "²",
    "name": "twosuperior",
    "codepoint": 178,
    "rows": [
      "##.",
      "..#",
      ".#.",
      "#..",
      "###"
    ],
    "x0": 0,
    "y0": 2,
    "advance": 4,
    "source": "drawn — a 3x5 digit at superscript height"
  },
  {
    "face": "VF Body",
    "char": "³",
    "name": "threesuperior",
    "codepoint": 179,
    "rows": [
      "##.",
      "..#",
      ".#.",
      "..#",
      "##."
    ],
    "x0": 0,
    "y0": 2,
    "advance": 4,
    "source": "drawn — a 3x5 digit at superscript height"
  },
  {
    "face": "VF Body",
    "char": "½",
    "name": "onehalf",
    "codepoint": 189,
    "rows": [
      ".#.......",
      "##...#...",
      ".#...#...",
      ".#..#....",
      "....#.##.",
      "...#....#",
      "...#...#.",
      "......###"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 10,
    "source": "drawn — mini 1 over mini 2 across a fraction slash, full cap band"
  },
  {
    "face": "VF Body",
    "char": "¼",
    "name": "onequarter",
    "codepoint": 188,
    "rows": [
      ".#.......",
      "##...#...",
      ".#...#...",
      ".#..#....",
      "....#.#.#",
      "...#..#.#",
      "...#..###",
      "........#"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 10,
    "source": "drawn — mini 1 over mini 4 across a fraction slash"
  },
  {
    "face": "VF Body",
    "char": "¾",
    "name": "threequarters",
    "codepoint": 190,
    "rows": [
      "##.......",
      "..#..#...",
      ".#...#...",
      "..#.#....",
      "##..#.#.#",
      "...#..#.#",
      "...#..###",
      "........#"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 10,
    "source": "drawn — the superscript ³ drawing over mini 4, matching ¼'s slash and denominator"
  },
  {
    "face": "VF Body",
    "char": "′",
    "name": "prime",
    "codepoint": 8242,
    "rows": [
      ".#",
      ".#",
      "#."
    ],
    "x0": 1,
    "y0": 4,
    "advance": 4,
    "source": "derived — the strike's ’ ink, dropped to sit on the x-height band"
  },
  {
    "face": "VF Body",
    "char": "″",
    "name": "doubleprime",
    "codepoint": 8243,
    "rows": [
      ".#..#",
      ".#..#",
      "#..#."
    ],
    "x0": 1,
    "y0": 4,
    "advance": 7,
    "source": "derived — two of the strike's ’ ink, one gap apart"
  },
  {
    "face": "VF Body",
    "char": "‚",
    "name": "quotesinglbase",
    "codepoint": 8218,
    "rows": [
      ".#",
      ".#",
      "#."
    ],
    "x0": 1,
    "y0": -2,
    "advance": 4,
    "source": "traced — the strike's comma, verbatim (a low-9 quote is a comma)"
  },
  {
    "face": "VF Body",
    "char": "„",
    "name": "quotedblbase",
    "codepoint": 8222,
    "rows": [
      ".#..#",
      ".#..#",
      "#..#."
    ],
    "x0": 1,
    "y0": -2,
    "advance": 7,
    "source": "derived — the strike's comma, doubled one gap apart"
  },
  {
    "face": "VF Body",
    "char": "‡",
    "name": "daggerdbl",
    "codepoint": 8225,
    "rows": [
      ".#.",
      "###",
      ".#.",
      ".#.",
      "###",
      ".#."
    ],
    "x0": 0,
    "y0": 2,
    "advance": 4,
    "source": "derived — the strike's † with its own crossbar repeated below"
  },
  {
    "face": "VF Body",
    "char": "‹",
    "name": "guilsinglleft",
    "codepoint": 8249,
    "rows": [
      "..#",
      ".#.",
      "#..",
      ".#.",
      "..#"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 5,
    "source": "derived — one chevron of the strike's «"
  },
  {
    "face": "VF Body",
    "char": "›",
    "name": "guilsinglright",
    "codepoint": 8250,
    "rows": [
      "#..",
      ".#.",
      "..#",
      ".#.",
      "#.."
    ],
    "x0": 1,
    "y0": 0,
    "advance": 5,
    "source": "derived — one chevron of the strike's », its bearing kept"
  },
  {
    "face": "VF Body",
    "char": "⁄",
    "name": "fraction",
    "codepoint": 8260,
    "rows": [
      "...#",
      "...#",
      "..#.",
      "..#.",
      ".#..",
      ".#..",
      "#...",
      "#..."
    ],
    "x0": 1,
    "y0": 0,
    "advance": 6,
    "source": "traced — the strike's /, verbatim (one drawing serves both slashes at 9pt)"
  },
  {
    "face": "VF Body",
    "char": "‰",
    "name": "perthousand",
    "codepoint": 8240,
    "rows": [
      ".#######...",
      "#..#..#....",
      "#..#.#.....",
      ".##..##.##.",
      "...##..#..#",
      "..#.#..#..#",
      ".#...##.##."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 12,
    "source": "derived — the strike's % with its lower loop doubled into a shared-wall 00 (Adam's ink, 2026-08-09)"
  },
  {
    "face": "VF Body",
    "char": "ﬁ",
    "name": "fi",
    "codepoint": 64257,
    "rows": [
      "..##.#",
      ".#....",
      "###.##",
      ".#...#",
      ".#...#",
      ".#...#",
      ".#...#"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 7,
    "source": "derived — the strike's f and i, joined at f's own advance"
  },
  {
    "face": "VF Body",
    "char": "ﬂ",
    "name": "fl",
    "codepoint": 64258,
    "rows": [
      "..####",
      ".#...#",
      "###..#",
      ".#...#",
      ".#...#",
      ".#...#",
      ".#...#"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 7,
    "source": "derived — the strike's f and l, joined at f's own advance"
  },
  {
    "face": "VF Body",
    "char": "Á",
    "name": "Aacute",
    "codepoint": 193,
    "rows": [
      "...#.",
      "..#..",
      ".....",
      "..#..",
      "..#..",
      ".#.#.",
      ".#.#.",
      "#####",
      "#...#",
      "#...#"
    ],
    "x0": 1,
    "y0": 0,
    "advance": 7,
    "source": "composed — the strike's A under its own acute"
  },
  {
    "face": "VF Body",
    "char": "Â",
    "name": "Acircumflex",
    "codepoint": 194,
    "rows": [
      "..#..",
      ".#.#.",
      ".....",
      "..#..",
      "..#..",
      ".#.#.",
      ".#.#.",
      "#####",
      "#...#",
      "#...#"
    ],
    "x0": 1,
    "y0": 0,
    "advance": 7,
    "source": "composed — the strike's A under its own circumflex"
  },
  {
    "face": "VF Body",
    "char": "È",
    "name": "Egrave",
    "codepoint": 200,
    "rows": [
      ".#..",
      "..#.",
      "....",
      "####",
      "#...",
      "#...",
      "###.",
      "#...",
      "#...",
      "####"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 5,
    "source": "composed — the strike's E under its own grave (its É, mirrored)"
  },
  {
    "face": "VF Body",
    "char": "Ê",
    "name": "Ecircumflex",
    "codepoint": 202,
    "rows": [
      ".#..",
      "#.#.",
      "....",
      "####",
      "#...",
      "#...",
      "###.",
      "#...",
      "#...",
      "####"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 5,
    "source": "composed — the strike's E under its own circumflex (placed as its ê)"
  },
  {
    "face": "VF Body",
    "char": "Ë",
    "name": "Edieresis",
    "codepoint": 203,
    "rows": [
      "#..#",
      "....",
      "####",
      "#...",
      "#...",
      "###.",
      "#...",
      "#...",
      "####"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 5,
    "source": "composed — the strike's E under its own dieresis (dots over the stems, as its ë)"
  },
  {
    "face": "VF Body",
    "char": "Ì",
    "name": "Igrave",
    "codepoint": 204,
    "rows": [
      "#.",
      ".#",
      "..",
      ".#",
      ".#",
      ".#",
      ".#",
      ".#",
      ".#",
      ".#"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 3,
    "source": "composed — the strike's I under its own grave (accent left of the stem, as its ì)"
  },
  {
    "face": "VF Body",
    "char": "Í",
    "name": "Iacute",
    "codepoint": 205,
    "rows": [
      ".#",
      "#.",
      "..",
      ".#",
      ".#",
      ".#",
      ".#",
      ".#",
      ".#",
      ".#"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 3,
    "source": "composed — the strike's I under its own acute (as its í)"
  },
  {
    "face": "VF Body",
    "char": "Î",
    "name": "Icircumflex",
    "codepoint": 206,
    "rows": [
      ".#.",
      "#.#",
      "...",
      ".#.",
      ".#.",
      ".#.",
      ".#.",
      ".#.",
      ".#.",
      ".#."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 4,
    "source": "composed — the strike's I under its own circumflex (as its î; a wider letter, like î vs í)"
  },
  {
    "face": "VF Body",
    "char": "Ï",
    "name": "Idieresis",
    "codepoint": 207,
    "rows": [
      "#.#",
      "...",
      ".#.",
      ".#.",
      ".#.",
      ".#.",
      ".#.",
      ".#.",
      ".#."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 4,
    "source": "composed — the strike's I under its own dieresis (as its ï)"
  },
  {
    "face": "VF Body",
    "char": "Ò",
    "name": "Ograve",
    "codepoint": 210,
    "rows": [
      ".#...",
      "..#..",
      ".....",
      ".###.",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      ".###."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 6,
    "source": "composed — the strike's O under its own grave"
  },
  {
    "face": "VF Body",
    "char": "Ó",
    "name": "Oacute",
    "codepoint": 211,
    "rows": [
      "...#.",
      "..#..",
      ".....",
      ".###.",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      ".###."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 6,
    "source": "composed — the strike's O under its own acute"
  },
  {
    "face": "VF Body",
    "char": "Ô",
    "name": "Ocircumflex",
    "codepoint": 212,
    "rows": [
      "..#..",
      ".#.#.",
      ".....",
      ".###.",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      ".###."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 6,
    "source": "composed — the strike's O under its own circumflex"
  },
  {
    "face": "VF Body",
    "char": "Ù",
    "name": "Ugrave",
    "codepoint": 217,
    "rows": [
      ".#...",
      "..#..",
      ".....",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      ".###."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 6,
    "source": "composed — the strike's U under its own grave"
  },
  {
    "face": "VF Body",
    "char": "Ú",
    "name": "Uacute",
    "codepoint": 218,
    "rows": [
      "...#.",
      "..#..",
      ".....",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      ".###."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 6,
    "source": "composed — the strike's U under its own acute"
  },
  {
    "face": "VF Body",
    "char": "Û",
    "name": "Ucircumflex",
    "codepoint": 219,
    "rows": [
      "..#..",
      ".#.#.",
      ".....",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      "#...#",
      ".###."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 6,
    "source": "composed — the strike's U under its own circumflex"
  },
  {
    "face": "VF Body",
    "char": "←",
    "name": "arrowleft",
    "codepoint": 8592,
    "rows": [
      "..#....",
      ".#.....",
      "#######",
      ".#.....",
      "..#...."
    ],
    "x0": 0,
    "y0": 1,
    "advance": 8,
    "source": "drawn — chevron-headed arrow on the math axis"
  },
  {
    "face": "VF Body",
    "char": "→",
    "name": "arrowright",
    "codepoint": 8594,
    "rows": [
      "....#..",
      ".....#.",
      "#######",
      ".....#.",
      "....#.."
    ],
    "x0": 0,
    "y0": 1,
    "advance": 8,
    "source": "drawn — chevron-headed arrow on the math axis"
  },
  {
    "face": "VF Body",
    "char": "↑",
    "name": "arrowup",
    "codepoint": 8593,
    "rows": [
      "..#..",
      ".#.#.",
      "#.#.#",
      "..#..",
      "..#..",
      "..#..",
      "..#.."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 6,
    "source": "drawn — chevron-headed arrow, cap height"
  },
  {
    "face": "VF Body",
    "char": "↓",
    "name": "arrowdown",
    "codepoint": 8595,
    "rows": [
      "..#..",
      "..#..",
      "..#..",
      "..#..",
      "#.#.#",
      ".#.#.",
      "..#.."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 6,
    "source": "drawn — chevron-headed arrow, cap height"
  },
  {
    "face": "VF Body",
    "char": "✕",
    "name": "multiplicationx",
    "codepoint": 10005,
    "rows": [
      "#.....#",
      ".#...#.",
      "..#.#..",
      "...#...",
      "..#.#..",
      ".#...#.",
      "#.....#"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 8,
    "source": "drawn — the ballot X: the × saltire at full cap size"
  },
  {
    "face": "VF Body",
    "char": "★",
    "name": "blackstar",
    "codepoint": 9733,
    "rows": [
      "...#...",
      "..###..",
      "#######",
      ".#####.",
      "..###..",
      ".##.##.",
      ".#...#."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 8,
    "source": "drawn — a five-point star filled solid, cap size (Adam's ink, 2026-08-09)"
  },
  {
    "face": "VF Body",
    "char": "⇧",
    "name": "shift",
    "codepoint": 8679,
    "rows": [
      "....#....",
      "...#.#...",
      "..#...#..",
      ".#.....#.",
      "##.....##",
      "..#...#..",
      "..#...#..",
      "..#...#..",
      "..#####.."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 10,
    "source": "drawn — the shift key outline (Adam's ink, 2026-08-09)"
  },
  {
    "face": "VF Body",
    "char": "⌥",
    "name": "option",
    "codepoint": 8997,
    "rows": [
      "##..###",
      "..#....",
      "...#...",
      "....#..",
      ".....##"
    ],
    "x0": 0,
    "y0": 1,
    "advance": 8,
    "source": "drawn — the option key switch"
  },
  {
    "face": "VF Body",
    "char": "⌃",
    "name": "control",
    "codepoint": 8963,
    "rows": [
      "..#..",
      ".#.#.",
      "#...#"
    ],
    "x0": 0,
    "y0": 3,
    "advance": 6,
    "source": "drawn — the control chevron, in the cap's upper band"
  },
  {
    "face": "VF Body",
    "char": "⎋",
    "name": "escape",
    "codepoint": 9099,
    "rows": [
      "###.....",
      "##..##..",
      "#.#...#.",
      "...#...#",
      ".#.....#",
      ".#.....#",
      "..#...#.",
      "...###.."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 9,
    "source": "drawn — the escape key: the arrow's shaft doubling as the ring's top-left arc (Adam's ink, 2026-08-10)"
  },
  {
    "face": "VF Body",
    "char": "⌫",
    "name": "deleteleft",
    "codepoint": 9003,
    "rows": [
      "...########",
      "..#.......#",
      ".#...#.#..#",
      "#.....#...#",
      ".#...#.#..#",
      "..#.......#",
      "...########"
    ],
    "x0": 0,
    "y0": 1,
    "advance": 12,
    "source": "drawn — the delete-back eraser pentagon around a 3x3 saltire"
  },
  {
    "face": "VF Body",
    "char": "⏎",
    "name": "returnsymbol",
    "codepoint": 9166,
    "rows": [
      "........#",
      "........#",
      "..#.....#",
      ".#......#",
      "#########",
      ".#.......",
      "..#......"
    ],
    "x0": 0,
    "y0": 1,
    "advance": 10,
    "source": "drawn — the return symbol, its head the text arrows' own chevron"
  },
  {
    "face": "VF Body",
    "char": "⇥",
    "name": "tabright",
    "codepoint": 8677,
    "rows": [
      "........#",
      "....#...#",
      ".....#..#",
      "#######.#",
      ".....#..#",
      "....#...#",
      "........#"
    ],
    "x0": 0,
    "y0": 1,
    "advance": 10,
    "source": "drawn — tab: the text arrow stopped by a bar"
  },
  {
    "face": "VF Body",
    "char": "⇤",
    "name": "tableft",
    "codepoint": 8676,
    "rows": [
      "#........",
      "#...#....",
      "#..#.....",
      "#.#######",
      "#..#.....",
      "#...#....",
      "#........"
    ],
    "x0": 0,
    "y0": 1,
    "advance": 10,
    "source": "drawn — back-tab, the ⇥'s mirror"
  },
  {
    "face": "VF Body",
    "char": "↩",
    "name": "hookarrowleft",
    "codepoint": 8617,
    "rows": [
      ".....###.",
      "........#",
      "..#.....#",
      ".#......#",
      "#########",
      ".#.......",
      "..#......"
    ],
    "x0": 0,
    "y0": 1,
    "advance": 10,
    "source": "drawn — the ⏎ with its tail curled instead of squared"
  },
  {
    "face": "VF Body",
    "char": "◆",
    "name": "diamond",
    "codepoint": 9670,
    "rows": [
      "...#...",
      "..###..",
      ".#####.",
      "#######",
      ".#####.",
      "..###..",
      "...#..."
    ],
    "x0": 0,
    "y0": 1,
    "advance": 8,
    "source": "traced — Chicago's ◆ (the classic symbol slot's ink), on Geneva's flush-left spacing"
  },
  {
    "face": "VF Body",
    "char": "",
    "name": "apple",
    "codepoint": 63743,
    "rows": [
      ".....##..",
      "....##...",
      "....#....",
      ".###.###.",
      "#########",
      "#######..",
      "#######..",
      "#########",
      "#########",
      ".#######.",
      "..##.##.."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 10,
    "source": "traced — Chicago's  menu apple, verbatim, like the ⌘ and ✓ before it"
  },
  {
    "face": "VF Body",
    "char": "●",
    "name": "blackcircle",
    "codepoint": 9679,
    "rows": [
      "..###..",
      ".#####.",
      "#######",
      "#######",
      "#######",
      ".#####.",
      "..###.."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 8,
    "source": "drawn — the strike's • disc grown to the 7px symbol cell"
  },
  {
    "face": "VF Body",
    "char": "○",
    "name": "whitecircle",
    "codepoint": 9675,
    "rows": [
      "..###..",
      ".#...#.",
      "#.....#",
      "#.....#",
      "#.....#",
      ".#...#.",
      "..###.."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 8,
    "source": "drawn — the ● as a 1px ring, the face's stroke"
  },
  {
    "face": "VF Body",
    "char": "■",
    "name": "blacksquare",
    "codepoint": 9632,
    "rows": [
      "#######",
      "#######",
      "#######",
      "#######",
      "#######",
      "#######",
      "#######"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 8,
    "source": "drawn — the 7px symbol cell filled solid"
  },
  {
    "face": "VF Body",
    "char": "□",
    "name": "whitesquare",
    "codepoint": 9633,
    "rows": [
      "#######",
      "#.....#",
      "#.....#",
      "#.....#",
      "#.....#",
      "#.....#",
      "#######"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 8,
    "source": "drawn — the ■ as a 1px ring"
  },
  {
    "face": "VF Body",
    "char": "◦",
    "name": "whitebullet",
    "codepoint": 9702,
    "rows": [
      ".###.",
      "#...#",
      "#...#",
      "#...#",
      ".###."
    ],
    "x0": 0,
    "y0": 1,
    "advance": 6,
    "source": "derived — the strike's own • hollowed to a ring, in its exact box and advance"
  },
  {
    "face": "VF Body",
    "char": "✗",
    "name": "ballotx",
    "codepoint": 10007,
    "rows": [
      "#.....#",
      ".#...#.",
      "..#.#..",
      "...#...",
      "..#.#..",
      ".#...#.",
      "#.....#"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 8,
    "source": "traced — the face's own ✕ (at strike sizes one X serves both codepoints)"
  },
  {
    "face": "VF Body",
    "char": "▸",
    "name": "smalltriangleright",
    "codepoint": 9656,
    "rows": [
      "#...",
      "##..",
      "###.",
      "####",
      "###.",
      "##..",
      "#..."
    ],
    "x0": 0,
    "y0": 1,
    "advance": 5,
    "source": "derived — the right half of the traced ◆ (the submenu wedge)"
  },
  {
    "face": "VF Body",
    "char": "◂",
    "name": "smalltriangleleft",
    "codepoint": 9666,
    "rows": [
      "...#",
      "..##",
      ".###",
      "####",
      ".###",
      "..##",
      "...#"
    ],
    "x0": 0,
    "y0": 1,
    "advance": 5,
    "source": "derived — the left half of the traced ◆"
  },
  {
    "face": "VF Body",
    "char": "▴",
    "name": "smalltriangleup",
    "codepoint": 9652,
    "rows": [
      "...#...",
      "..###..",
      ".#####.",
      "#######"
    ],
    "x0": 0,
    "y0": 1,
    "advance": 8,
    "source": "derived — the top half of the traced ◆"
  },
  {
    "face": "VF Body",
    "char": "▾",
    "name": "smalltriangledown",
    "codepoint": 9662,
    "rows": [
      "#######",
      ".#####.",
      "..###..",
      "...#..."
    ],
    "x0": 0,
    "y0": 1,
    "advance": 8,
    "source": "derived — the bottom half of the traced ◆"
  },
  {
    "face": "VF Body",
    "char": "▶",
    "name": "triangleright",
    "codepoint": 9654,
    "rows": [
      "#....",
      "##...",
      "###..",
      "####.",
      "#####",
      "####.",
      "###..",
      "##...",
      "#...."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 6,
    "source": "drawn — the ▸ wedge grown to the ⌘'s 9px band"
  },
  {
    "face": "VF Body",
    "char": "◀",
    "name": "triangleleft",
    "codepoint": 9664,
    "rows": [
      "....#",
      "...##",
      "..###",
      ".####",
      "#####",
      ".####",
      "..###",
      "...##",
      "....#"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 6,
    "source": "drawn — the ▶'s mirror"
  },
  {
    "face": "VF Body",
    "char": "☆",
    "name": "whitestar",
    "codepoint": 9734,
    "rows": [
      "...#...",
      "..#.#..",
      "##...##",
      ".#...#.",
      "..#.#..",
      ".##.##.",
      ".#...#."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 8,
    "source": "drawn — the ★'s outline by the display ☆'s construction — PROPOSAL: this is the 7x7 that awaited a sketch; veto freely"
  },
  {
    "face": "VF Body",
    "char": "‑",
    "name": "nonbreakinghyphen",
    "codepoint": 8209,
    "rows": [
      "####"
    ],
    "x0": 0,
    "y0": 3,
    "advance": 5,
    "source": "traced — the strike's hyphen, verbatim (the hyphen that refuses the break)"
  },
  {
    "face": "VF Body",
    "char": "­",
    "name": "softhyphen",
    "codepoint": 173,
    "rows": [
      "####"
    ],
    "x0": 0,
    "y0": 3,
    "advance": 5,
    "source": "traced — the strike's hyphen, verbatim (visible only where a line breaks)"
  },
  {
    "face": "VF Body",
    "char": " ",
    "name": "figurespace",
    "codepoint": 8199,
    "rows": [
      "......"
    ],
    "x0": 0,
    "y0": 0,
    "advance": 6,
    "source": "derived — no ink: the strike's own 6px digit advance, so numerals stay columnar"
  },
  {
    "face": "VF Body",
    "char": " ",
    "name": "thinspace",
    "codepoint": 8201,
    "rows": [
      ".."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 2,
    "source": "derived — no ink: 2px, one step under the strike's 3px word space"
  },
  {
    "face": "VF Body",
    "char": " ",
    "name": "hairspace",
    "codepoint": 8202,
    "rows": [
      "."
    ],
    "x0": 0,
    "y0": 0,
    "advance": 1,
    "source": "derived — no ink: the 1px minimum the pixel grid can state"
  }
]
