/**
 * The embedded System 7 pointer set — GENERATED by `npm run embed:cursors`
 * from `cursors/*.png`; edit the art there (or the hotspot/XOR manifest in
 * `scripts/embed-cursor-art.mjs`) and re-run rather than editing this file.
 *
 * Like the bitmap faces, the art ships base64-embedded so the package needs
 * no asset files: these are the defaults `applyCursor()` uses, exported so a
 * consumer can pass one explicitly, remap it to another kind, or mix the set
 * with art of their own. XOR art carries a `staticSrc` variant — the same
 * ink under a one-pixel white halo — for the engines whose top layer cannot
 * blend; supply `cursors/<name>-static.png` to replace the generated halo
 * with hand-drawn art.
 */
import type { VfCursorArt } from './cursor.js'

/**
 * The System 7 arrow. Hotspot on the black tip at (1,1), inside the
 * white outline whose corner is (0,0); the outline is what keeps it legible
 * on any background, so it draws as-is rather than with the XOR pen.
 */
export const CURSOR_ARROW: VfCursorArt = {
  src: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAAQCAYAAADAvYV+AAAAS0lEQVR42q2SMQ4AMAgC/f+n20WTliowlNW7RA2xMuEkQU8o2BJOWAoIU6GDR2GCW4HBj6DgS2A7Y7o/6wNrSAXshoS/VcAuGK64ASXf4R9SU/euAAAAAElFTkSuQmCC',
  width: 11,
  height: 16,
  hotspotX: 1,
  hotspotY: 1,
}

/**
 * The text-entry I-beam. Hotspot mid-stem, per the classic CURS
 * resource; draws with the XOR pen, as System 7 drew it, with a white-halo
 * static variant for the engines that cannot (see `staticSrc`).
 */
export const CURSOR_I_BEAM: VfCursorArt = {
  src: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAASCAYAAACJgPRIAAAAJElEQVR42mNgIAH8h2JCYnAJBlyS2BSOKhpaivBGMElJBSsAAPlIF+m2BB32AAAAAElFTkSuQmCC',
  staticSrc: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAASCAYAAACJgPRIAAAAOklEQVR42mP4jwYYGBgYMMSgEv/R5ZDFGNAlkGlk0xmQrUBWwIANoJnGMKqIlorwRgtREUxyUsGV6AB8JyboJ0V9MQAAAABJRU5ErkJggg==',
  width: 9,
  height: 18,
  hotspotX: 4,
  hotspotY: 8,
  invert: true,
}

/**
 * The crosshair. Hotspot on the intersection; draws with the XOR pen,
 * as System 7 drew it, with a white-halo static variant for the engines
 * that cannot (see `staticSrc`).
 */
export const CURSOR_CROSSHAIR: VfCursorArt = {
  src: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAHElEQVR42mNgoDH4P2oAHQ34TyYeDcSRYQBBAAA+6BrmCTIofgAAAABJRU5ErkJggg==',
  staticSrc: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAMElEQVR42mNgwAH+IwEGcgBU46gBxBjwHw8gIA1RA1NIDoYbQJELRqNxsBtATHYGAOqhCgWyPk7UAAAAAElFTkSuQmCC',
  width: 16,
  height: 16,
  hotspotX: 7,
  hotspotY: 7,
  invert: true,
}

/**
 * The wristwatch, 8 frames of turning hand. Opaque white face, so it
 * reads on any background drawn as-is.
 */
export const CURSOR_WAIT: VfCursorArt = {
  src: [
    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAANElEQVR42mNgwA7+48BEgyFuwH9cgBhDsGoixRC6GfCfoAHIgUeWAeQGJMUGUByNIzEvAAD+3h7wGXnswAAAAABJRU5ErkJggg==',
    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAOUlEQVR42mNgwA7+48BEgyFuwH9cgBhD/hMChAzBq5FsA5DFCYUHNoXYvPCf/mFAlZggKS2MoLwAABZGIe0u7mf5AAAAAElFTkSuQmCC',
    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAMklEQVR42mNgwA7+48BEgyFuwH9cgBhD/hMChAyhmwH/CRqALRBJMmDAwoDiaByJeQEAXRsh7d6Ez7cAAAAASUVORK5CYII=',
    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAANElEQVR42mNgwA7+48BEgyFuwH9cgBhD/hMChAyhmwH/CRqAHHhkGYCuiW5hQHE0jsS8AAC0GCTqSlaRPQAAAABJRU5ErkJggg==',
    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAANklEQVR42mNgwA7+48BEgyFuwH9cgBhD/hMChAyhmwH/CRqAHHhkGYCsgSIvkGoAxdE4EvMCAIAUIe3WmwVMAAAAAElFTkSuQmCC',
    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAOUlEQVR42mNgwA7+48BEgyFuwH9cgBhD/hMChAyhmwH/CRqAHHhkGQBTTLYXcHmHopggKS2MoLwAAFw4Ie372GT7AAAAAElFTkSuQmCC',
    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAMklEQVR42mNgwA7+48BEgyFuwH9cgBhD/hMChAyhmwH/8RqAHngkGzCgYUBxNI7EvAAAwfwk6qpQGA8AAAAASUVORK5CYII=',
    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAOElEQVR42mNgwA7+48BEgyFuwH9cgBhD/hMChAxBUUiRAbgMIRQe2BSSZwDFYUCTmCApLYygvAAAzn8h7Z3ZHmwAAAAASUVORK5CYII=',
  ],
  width: 16,
  height: 16,
  hotspotX: 8,
  hotspotY: 8,
}
