/**
 * The embedded System 7 pointer set — GENERATED by `npm run embed:cursors`
 * from `cursors/*.png`; edit the art there (or the hotspot/XOR manifest in
 * `scripts/embed-cursor-art.mjs`) and re-run rather than editing this file.
 *
 * Like the bitmap faces, the art ships base64-embedded so the package needs
 * no asset files: these are the defaults `applyCursor()` uses, exported so a
 * consumer can pass one explicitly, remap it to another kind, or mix the set
 * with art of their own.
 */
import type { VfCursorArt } from './cursor.js'

/**
 * The System 7 arrow. Hotspot on the black tip at (1,1), inside the
 * white outline whose corner is (0,0); the outline is what keeps it legible
 * on any background, so it draws as-is rather than with the XOR pen.
 */
export const CURSOR_ARROW: VfCursorArt = {
  src: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAAQCAYAAADAvYV+AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAOdEVYdFNvZnR3YXJlAEZpZ21hnrGWYwAAAGNJREFUeAGNkEsKADEIQ1V6/yt3EJQpkrRxUazkxY/tChMi8nF3U4DoRAHi/LyAmIUbEKjIAChmABUj4CqewGKiOXICawrS6XB1QzOX0NuRLthCewW6Z9V2pf81JMfeQenYhh8vwlEBxMajqAAAAABJRU5ErkJggg==',
  width: 11,
  height: 16,
  hotspotX: 1,
  hotspotY: 1,
}

/**
 * The text-entry I-beam. Hotspot mid-stem, per the classic CURS
 * resource; draws with the XOR pen, as System 7 drew it.
 */
export const CURSOR_I_BEAM: VfCursorArt = {
  src: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAcAAAAQCAYAAADagWXwAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAOdEVYdFNvZnR3YXJlAEZpZ21hnrGWYwAAADFJREFUeAHt0bERACAIBMF7++/5DQx0VKABNr0h4QWYRWzm4ih8LwaJjlU8PY8XyWQT0zgJEvDD2K8AAAAASUVORK5CYII=',
  width: 7,
  height: 16,
  hotspotX: 3,
  hotspotY: 7,
  invert: true,
}

/**
 * The crosshair. Hotspot on the intersection; draws with the XOR pen,
 * as System 7 drew it.
 */
export const CURSOR_CROSSHAIR: VfCursorArt = {
  src: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAOCAYAAAAfSC3RAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAOdEVYdFNvZnR3YXJlAEZpZ21hnrGWYwAAACxJREFUeAHt0bENADAIA8FP9t8ZJgCkb+Fay40NtWgyPtKG4mNYz7g7kHQxAVnfAxVWEyxsAAAAAElFTkSuQmCC',
  width: 14,
  height: 14,
  hotspotX: 6,
  hotspotY: 6,
  invert: true,
}

/**
 * The wristwatch, 8 frames of turning hand. Opaque white face, so it
 * reads on any background drawn as-is.
 */
export const CURSOR_WAIT: VfCursorArt = {
  src: [
    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAOdEVYdFNvZnR3YXJlAEZpZ21hnrGWYwAAAFNJREFUeAHlk8EOABAMQ1X8/y8jYiKsBIcd9EJqfRkyOF2R+BgN7x5lD4DixSy9GJgyfheuITksywpwrFtA6yKwir71lSiAPaTwZWP/jeyiP81CAiQvFhxs9F2QAAAAAElFTkSuQmCC',
    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAOdEVYdFNvZnR3YXJlAEZpZ21hnrGWYwAAAFtJREFUeAHdk0sKACAIRJ3o/lfuAyFUmlaLoNk1OM80AslKio/RCHSp9wAIXiqSi4EpA29Yg7hHaMFJLkANDzfjQ1yFuHoxlgowdrG/A5PUNz9/RoaQs+EHfyEDxMoYICH7fTEAAAAASUVORK5CYII=',
    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAOdEVYdFNvZnR3YXJlAEZpZ21hnrGWYwAAAE9JREFUeAHdU0EKACAIc9H/v1wdQqgcCQlCOw43dSLERiM8dqLII/INYHBtwC4GDg28YmaSloGOWVnFHHVVGetRg0sWcRmEn1FNxNnwg1/oSFwVHbqi8WMAAAAASUVORK5CYII=',
    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAOdEVYdFNvZnR3YXJlAEZpZ21hnrGWYwAAAFZJREFUeAHdk9sKACAIQ130/7/chSKiVIwCIR/HdlpGIH6SoGMVAl2OPwCMlsrwZmDLwBqWIG47GDWj5OhVm1u5lgiYQxW2QM52oDV4/owDQsYDP/gLGVO3Gxq9iFvdAAAAAElFTkSuQmCC',
    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAOdEVYdFNvZnR3YXJlAEZpZ21hnrGWYwAAAFFJREFUeAHdU1sKACAIc9H9r9yDwo9SERKE9jm2tRRBMprC4yQKPSI/AALXBmQxcHngNWshaTPgmlVT7KpLbXxLbTBNhjFuBuFr5BByPvjBLXRTBhgYClRrJAAAAABJRU5ErkJggg==',
    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAOdEVYdFNvZnR3YXJlAEZpZ21hnrGWYwAAAFlJREFUeAHdU1sKACAMmtH9r9yDHlDNivoI2qeoM2MQfRzB0QNGLue9ARTMhdHJwKDBrpiZPOugxrSMkaMm9uRZNEEREfG6g5hgVWjj1C4//8ZqIpsLP7gFD39aGxhusMEtAAAAAElFTkSuQmCC',
    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAOdEVYdFNvZnR3YXJlAEZpZ21hnrGWYwAAAFBJREFUeAHdU0EKACAIc9H/v1wdoqBmCQlCO06dOhHCURQeK5HkEfECIFxp4MnAVgNrsSYS5sEYM7NoH3NmH9aiAjcfxNMD9zMOETE2/OAXKmxEFR2vuADhAAAAAElFTkSuQmCC',
    'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAOdEVYdFNvZnR3YXJlAEZpZ21hnrGWYwAAAFNJREFUeAHdk0kKACAMAxvx/1+uevGgXQIKgnMM7RgUITbq5FiDIoe8F8DItGMPA9sO2GVPUpLBFFcwmgQSpRtkTaoEDQLyO2C5/oxTIuSBH/yFBlXfFSRE94DbAAAAAElFTkSuQmCC',
  ],
  width: 16,
  height: 16,
  hotspotX: 8,
  hotspotY: 8,
}
