/**
 * The kit's embedded raster art — the counterpart to glyphs.ts.
 *
 * glyphs.ts holds the 1-bit *glyphs* (a checkmark, a caret, the little
 * arrows): geometry, so they are drawn as inline SVG. This holds the one
 * thing the kit draws that is a *picture* — the 32x32 System 7 alert icon —
 * and a picture is not vectorized. It ships as the raster it was drawn as,
 * magnified nearest-neighbor on the system-pixel grid, which is what vf-img
 * does for a consumer's own art.
 *
 * The art is black ink on transparency, so it is used as a *mask* over
 * `--vf-black` rather than as an `<img>`: the ink then follows the token
 * like every other 1-bit surface in the kit, and the transparent interior
 * lets the alert's own surface show through the triangle — a raster that
 * still themes. `npm run verify:caution` asserts the rendered ink.
 *
 * GENERATED by `npm run extract:icons` — do not edit the data by hand.
 * The crop lives in scripts/extract-da-icons.py (LARGE_ICONS).
 */

/** The 32x32 System 7 caution icon, as a PNG data URI. */
export const CAUTION_ICON = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAlklEQVR4nOWWSxLAIAhDvf+l7aab0spHSbKoM+wgeTMoOMbZmXdIzjTxLwBrSoeQAqzMaBBSgMgEDhH1HgqwMqNBSAG+RL1B1A4hBYieHfxZSgE8kcwyOoaQAmSnHmw6SgEyRZUPSRkiW9CdV06G5KKWSUoXvc9D/SpAa/6uWBuEFGC392116MvnArDNX762l+x40NDNL0DL8Q/AL69+AAAAAElFTkSuQmCC'
